---
title: "Analysis of Interaction between Boroughs and Weekend"
author: "Junhong Liu"
date: "11/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("feather")
#install.packages("arrow")
library(feather)
library(arrow)
```

```{r read in the processed feather file, echo = FALSE}
filepath <- "./preprocessed_data/"
dailyEarnings <- arrow::read_feather(paste0(filepath, "boroughsDailyEarnings.feather"))
dailyEarnings <- as.data.frame(dailyEarnings)
dailyEarnings$Borough <- as.factor(dailyEarnings$Borough)
dailyEarnings$Weekend <- as.factor(dailyEarnings$Weekend)
```

## Setting up the three models

Three models are defined, the model with interaction between Weekend and Borough, the model without interaction, and the model with just Borough as a predictor variable.

```{r interaction testing, echo=FALSE}
interactionModel = lm(logDE ~ Weekend * Borough, data = dailyEarnings)
summary(interactionModel)

additiveModel = lm(logDE ~ Weekend + Borough, data = dailyEarnings)
summary(additiveModel)

boroughModel = lm(logDE ~ Borough, data = dailyEarnings)
summary(boroughModel)
```
```{r, echo=FALSE}
anova(additiveModel, interactionModel)

anova(additiveModel, boroughModel)
```


